[licenses]
allow-osi-fsf-free = "both"
exceptions = [
    { allow = ["MPL-2.0"], name = "option-ext" },
    { allow = ["Unicode-DFS-2016"], name = "unicode-ident" },
]

[licenses.private]
ignore = true

[bans]
skip = [
    { name = "bitflags", version = "1" },
    { name = "syn", version = "1" },
]

skip-tree = [
    { name = "windows-sys", version = "0.48", depth = 3 },
]
